x-common-variables: &common-vars
  ARCH: arm64

services:
  kernel-config:
    platform: "linux/arm64"
    build:
      context: .
    image: rpi-toolchain
    container_name: kernel-config
    environment: *common-vars
    volumes:
      - ./conf:/conf
    tmpfs:
      - /build:rw,exec,size=12G,mode=1777
    command:
      - bash
      - -c
      - |
        set -euo pipefail
        chown -R builder:builder /conf
        su builder -c "
          mkdir -p /build/linux-rpi
          cp -a /src/. /build/linux-rpi/
          cd /build/linux-rpi
          make bcm2712_defconfig
          make menuconfig
          cp .config /conf/.config
        "

  kernel-builder:
    platform: "linux/arm64"
    build:
      context: .
    image: rpi-toolchain
    container_name: kernel-builder
    environment: *common-vars
    volumes:
      - ./out:/out
      - ./conf/.config:/tmp/.config:ro
    tmpfs:
      - /build:rw,exec,size=12G,mode=1777
    command:
      - bash
      - -c
      - |
        set -euo pipefail
        chown -R builder:builder /out /build
        su builder -c "
          mkdir -p /build/linux-rpi /out/overlays
          cp -a /src/. /build/linux-rpi/
          cd /build/linux-rpi
          cp /tmp/.config .config
          make -j$(nproc) Image.gz modules dtbs KCFLAGS='-mcpu=native'
          make -j$(nproc) INSTALL_MOD_PATH=/out modules_install
          cp arch/arm64/boot/Image /out/kernel_2712.img
          cp arch/arm64/boot/dts/broadcom/*.dtb /out/
          cp arch/arm64/boot/dts/overlays/*.dtbo /out/overlays/
          cp arch/arm64/boot/dts/overlays/README /out/overlays/
        "